const rates={amazon:.925,apple:.89,steam:.86,visa:.845,google:.82};
const typeKey={Amazon:'amazon','Apple Gift Card':'apple',Steam:'steam','Visa Prepaid':'visa','Google Play':'google'};
const cardType=document.querySelector('#cardType'),cardValue=document.querySelector('#cardValue'),estimate=document.querySelector('#estimate');
function updateEstimate(){const key=cardType.value;const value=Math.max(0,Number(cardValue.value)||0);estimate.textContent=`$${(value*(rates[key]||.85)).toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2})}`}
function openModal(){const modal=document.querySelector('#tradeModal');modal.classList.add('open');modal.setAttribute('aria-hidden','false');document.querySelector('#formValue').value=cardValue.value;document.querySelector('#formCardType').value=cardType.options[cardType.selectedIndex].text;document.querySelector('#tradeForm').style.display='block';document.querySelector('#success').classList.remove('show');setTimeout(()=>document.querySelector('#name').focus(),80)}
function closeModal(){const modal=document.querySelector('#tradeModal');modal.classList.remove('open');modal.setAttribute('aria-hidden','true')}
function toast(text){const t=document.querySelector('#toast');t.textContent=text;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2400)}
cardType.addEventListener('change',updateEstimate);cardValue.addEventListener('input',updateEstimate);updateEstimate();
document.querySelectorAll('[data-open-form]').forEach(button=>button.addEventListener('click',openModal));document.querySelectorAll('[data-close]').forEach(button=>button.addEventListener('click',closeModal));document.querySelector('#tradeModal').addEventListener('click',e=>{if(e.target.id==='tradeModal')closeModal()});document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal()});
document.querySelector('#tradeForm').addEventListener('submit',e=>{e.preventDefault();const id=`CS-${Math.random().toString(36).slice(2,8).toUpperCase()}`;document.querySelector('#tradeId').textContent=id;setTelegramTradeLink(id);document.querySelector('#tradeForm').style.display='none';document.querySelector('#success').classList.add('show');toast('Application submitted for manual review')});
const chatPanel=document.querySelector('#chatPanel'),chatMessages=document.querySelector('#chatMessages');
function openChat(){chatPanel.classList.add('open');chatPanel.setAttribute('aria-hidden','false');setTimeout(()=>document.querySelector('#chatInput').focus(),100)}
function setTelegramTradeLink(id){document.querySelector('#telegramContinue').href=`https://t.me/cardspring_exchange?start=${encodeURIComponent(id)}`}
function closeChat(){chatPanel.classList.remove('open');chatPanel.setAttribute('aria-hidden','true')}
document.querySelector('[data-close-chat]').addEventListener('click',closeChat);document.querySelector('#cardEvidence').addEventListener('change',e=>{const file=e.target.files[0];document.querySelector('#attachmentName').textContent=file?`Attached: ${file.name}`:''});
document.querySelector('#chatForm').addEventListener('submit',e=>{e.preventDefault();const input=document.querySelector('#chatInput');const text=input.value.trim();const file=document.querySelector('#cardEvidence').files[0];if(!text&&!file)return;const body=[text,file?`Attached: ${file.name}`:''].filter(Boolean).join('\n');chatMessages.insertAdjacentHTML('beforeend',`<div class="message customer"><p>${body.replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]))}</p><small>Just now</small></div>`);input.value='';document.querySelector('#attachmentName').textContent='';document.querySelector('#cardEvidence').value='';chatMessages.scrollTop=chatMessages.scrollHeight;setTimeout(()=>{chatMessages.insertAdjacentHTML('beforeend','<div class="message agent"><span>CS</span><p>Received. I’m reviewing your submission now and will reply here with the verification result and next payout step.</p><small>Just now</small></div>');chatMessages.scrollTop=chatMessages.scrollHeight},900)});
document.querySelector('#success [data-close]').addEventListener('click',()=>{closeModal();openChat()});
